# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ambreen Hanif


description: >- # this means to ignore newlines until "baseurl:"
 Welcome to My Ideation Space and my Learning Journey, a personal blog where I document my adventures in the world of technology. As I explore new tools, languages, and frameworks, I share my learning, experiences, and tutorials to help fellows on a similar learning journey. Join me as we demystify technology, one post at a time!
 P.S. Not a smooth ride but this is worth the struggle. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#github: [metadata] 
#encoding: UTF-8 

name: Ambreen Hanif
email: hanif.ambreen@[gmaildotcom]
# Build settings
theme: minima
#skin: dark
#date_format: "%Y-%m-%d %H:%M"
#social_links:
    #twitter_username: umbreenh
github_username:  umberH
linkedin_username: ambreen16


#remote_theme: pages-themes/cayman@v0.2.0
plugins:
  #- jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

reading_time:
  second_plural: "sec"    # default: seconds
  minute_singular: "min"  # default: minute
  minute_plural: "min"    # default: minutes

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#ignore_theme_config: true
